//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWLWebAPI.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class CBEMSDGXXEntities : DbContext
    {
        public CBEMSDGXXEntities()
            : base("name=CBEMSDGXXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<collector> collector { get; set; }
        public DbSet<dtproperties> dtproperties { get; set; }
        public DbSet<StandardValue> StandardValue { get; set; }
        public DbSet<tbAirconditionCollectedMap> tbAirconditionCollectedMap { get; set; }
        public DbSet<tbAirconditionGrade> tbAirconditionGrade { get; set; }
        public DbSet<tbAirconditionSurvey> tbAirconditionSurvey { get; set; }
        public DbSet<tbAirconditionSurveyDetail> tbAirconditionSurveyDetail { get; set; }
        public DbSet<tbAirEfficiency> tbAirEfficiency { get; set; }
        public DbSet<tbAlarmConditon> tbAlarmConditon { get; set; }
        public DbSet<tbAlarmRecord> tbAlarmRecord { get; set; }
        public DbSet<tbBaseFee> tbBaseFee { get; set; }
        public DbSet<tbBuildInfor> tbBuildInfor { get; set; }
        public DbSet<tbBuildStruct> tbBuildStruct { get; set; }
        public DbSet<tbControlCollection> tbControlCollection { get; set; }
        public DbSet<tbDailyRecord_CoolHeat> tbDailyRecord_CoolHeat { get; set; }
        public DbSet<tbDailyRecord_Oil> tbDailyRecord_Oil { get; set; }
        public DbSet<tbDailyRecord_Tran> tbDailyRecord_Tran { get; set; }
        public DbSet<tbDailyRecord_Water> tbDailyRecord_Water { get; set; }
        public DbSet<tbDayByHourList> tbDayByHourList { get; set; }
        public DbSet<tbDayByMinuteList> tbDayByMinuteList { get; set; }
        public DbSet<tbDivision> tbDivision { get; set; }
        public DbSet<tbEmailParameter> tbEmailParameter { get; set; }
        public DbSet<tbEnergyCollection> tbEnergyCollection { get; set; }
        public DbSet<tbEnergyCollection_ByDay> tbEnergyCollection_ByDay { get; set; }
        public DbSet<tbEnergyCollection_ByHour> tbEnergyCollection_ByHour { get; set; }
        public DbSet<tbEnergyFPGPower> tbEnergyFPGPower { get; set; }
        public DbSet<tbEnergyofDivisionDetail> tbEnergyofDivisionDetail { get; set; }
        public DbSet<tbEnergyofDivisionHearder> tbEnergyofDivisionHearder { get; set; }
        public DbSet<tbEnergyShape> tbEnergyShape { get; set; }
        public DbSet<tbEnergysubSurvey> tbEnergysubSurvey { get; set; }
        public DbSet<tbEnergySurvey> tbEnergySurvey { get; set; }
        public DbSet<tbEnergySurveyHeader> tbEnergySurveyHeader { get; set; }
        public DbSet<tbEquipment> tbEquipment { get; set; }
        public DbSet<tbEquipmentMaintRecord> tbEquipmentMaintRecord { get; set; }
        public DbSet<tbEquipmentRunRecord> tbEquipmentRunRecord { get; set; }
        public DbSet<tbExpertDoc> tbExpertDoc { get; set; }
        public DbSet<tbGradeDetail> tbGradeDetail { get; set; }
        public DbSet<tbGradeHeader> tbGradeHeader { get; set; }
        public DbSet<tbGroup> tbGroup { get; set; }
        public DbSet<tbGroupStaff> tbGroupStaff { get; set; }
        public DbSet<tbImageMarkerDetail> tbImageMarkerDetail { get; set; }
        public DbSet<tbImageMarkerHeader> tbImageMarkerHeader { get; set; }
        public DbSet<tbLightEfficiency> tbLightEfficiency { get; set; }
        public DbSet<tbLimitedTarget> tbLimitedTarget { get; set; }
        public DbSet<tbLoginInfor> tbLoginInfor { get; set; }
        public DbSet<tbLookupDetail> tbLookupDetail { get; set; }
        public DbSet<tbLookupHeader> tbLookupHeader { get; set; }
        public DbSet<tbLoopMap_OPC> tbLoopMap_OPC { get; set; }
        public DbSet<tbLoopMapping> tbLoopMapping { get; set; }
        public DbSet<tbMenuView> tbMenuView { get; set; }
        public DbSet<tbModel> tbModel { get; set; }
        public DbSet<tbPowerCollection> tbPowerCollection { get; set; }
        public DbSet<tbQueryCondition> tbQueryCondition { get; set; }
        public DbSet<tbRegion> tbRegion { get; set; }
        public DbSet<tbReportList> tbReportList { get; set; }
        public DbSet<tbStaff> tbStaff { get; set; }
        public DbSet<tbStaffPurview> tbStaffPurview { get; set; }
        public DbSet<tbSystemParameter> tbSystemParameter { get; set; }
        public DbSet<Tbuserenergymap> Tbuserenergymap { get; set; }
        public DbSet<tmp_CollectionMaxId> tmp_CollectionMaxId { get; set; }
        public DbSet<tmp_EnergyChart> tmp_EnergyChart { get; set; }
        public DbSet<tmp_EnergyCollection> tmp_EnergyCollection { get; set; }
        public DbSet<tmp_EnergyCollection_ByDay> tmp_EnergyCollection_ByDay { get; set; }
        public DbSet<tmp_EnergyCollection_ByHour> tmp_EnergyCollection_ByHour { get; set; }
        public DbSet<tmp_EnergySurvey> tmp_EnergySurvey { get; set; }
        public DbSet<tmp_EnergySurveyHeader> tmp_EnergySurveyHeader { get; set; }
        public DbSet<tmp_S_EnergyCollection> tmp_S_EnergyCollection { get; set; }
        public DbSet<vwEnergy_Today_byUser> vwEnergy_Today_byUser { get; set; }
        public DbSet<vwEnergyofUser_ByHour> vwEnergyofUser_ByHour { get; set; }
        public DbSet<vwEnergysubSurvey> vwEnergysubSurvey { get; set; }
        public DbSet<vwEnergySurvey> vwEnergySurvey { get; set; }
    
        [EdmFunction("CBEMSDGXXEntities", "F_ListDivisionByParent")]
        public virtual IQueryable<F_ListDivisionByParent_Result> F_ListDivisionByParent(string parent)
        {
            var parentParameter = parent != null ?
                new ObjectParameter("parent", parent) :
                new ObjectParameter("parent", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_ListDivisionByParent_Result>("[CBEMSDGXXEntities].[F_ListDivisionByParent](@parent)", parentParameter);
        }
    
        public virtual ObjectResult<Ca_aircondE1_Result> Ca_aircondE1(Nullable<System.DateTime> datetime)
        {
            var datetimeParameter = datetime.HasValue ?
                new ObjectParameter("Datetime", datetime) :
                new ObjectParameter("Datetime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ca_aircondE1_Result>("Ca_aircondE1", datetimeParameter);
        }
    
        public virtual ObjectResult<Ca_airCondE2_Result> Ca_airCondE2(Nullable<System.DateTime> dateTime)
        {
            var dateTimeParameter = dateTime.HasValue ?
                new ObjectParameter("DateTime", dateTime) :
                new ObjectParameter("DateTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ca_airCondE2_Result>("Ca_airCondE2", dateTimeParameter);
        }
    
        public virtual int CMDataToCbems()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CMDataToCbems");
        }
    
        public virtual int CMDataToCbems_2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CMDataToCbems_2");
        }
    
        public virtual int dt_addtosourcecontrol(string vchSourceSafeINI, string vchProjectName, string vchComment, string vchLoginName, string vchPassword)
        {
            var vchSourceSafeINIParameter = vchSourceSafeINI != null ?
                new ObjectParameter("vchSourceSafeINI", vchSourceSafeINI) :
                new ObjectParameter("vchSourceSafeINI", typeof(string));
    
            var vchProjectNameParameter = vchProjectName != null ?
                new ObjectParameter("vchProjectName", vchProjectName) :
                new ObjectParameter("vchProjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_addtosourcecontrol", vchSourceSafeINIParameter, vchProjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_addtosourcecontrol_u(string vchSourceSafeINI, string vchProjectName, string vchComment, string vchLoginName, string vchPassword)
        {
            var vchSourceSafeINIParameter = vchSourceSafeINI != null ?
                new ObjectParameter("vchSourceSafeINI", vchSourceSafeINI) :
                new ObjectParameter("vchSourceSafeINI", typeof(string));
    
            var vchProjectNameParameter = vchProjectName != null ?
                new ObjectParameter("vchProjectName", vchProjectName) :
                new ObjectParameter("vchProjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_addtosourcecontrol_u", vchSourceSafeINIParameter, vchProjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_adduserobject()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_adduserobject");
        }
    
        public virtual int dt_adduserobject_vcs(string vchProperty)
        {
            var vchPropertyParameter = vchProperty != null ?
                new ObjectParameter("vchProperty", vchProperty) :
                new ObjectParameter("vchProperty", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_adduserobject_vcs", vchPropertyParameter);
        }
    
        public virtual int dt_checkinobject(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag, string txStream1, string txStream2, string txStream3)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            var txStream1Parameter = txStream1 != null ?
                new ObjectParameter("txStream1", txStream1) :
                new ObjectParameter("txStream1", typeof(string));
    
            var txStream2Parameter = txStream2 != null ?
                new ObjectParameter("txStream2", txStream2) :
                new ObjectParameter("txStream2", typeof(string));
    
            var txStream3Parameter = txStream3 != null ?
                new ObjectParameter("txStream3", txStream3) :
                new ObjectParameter("txStream3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkinobject", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter, txStream1Parameter, txStream2Parameter, txStream3Parameter);
        }
    
        public virtual int dt_checkinobject_u(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag, string txStream1, string txStream2, string txStream3)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            var txStream1Parameter = txStream1 != null ?
                new ObjectParameter("txStream1", txStream1) :
                new ObjectParameter("txStream1", typeof(string));
    
            var txStream2Parameter = txStream2 != null ?
                new ObjectParameter("txStream2", txStream2) :
                new ObjectParameter("txStream2", typeof(string));
    
            var txStream3Parameter = txStream3 != null ?
                new ObjectParameter("txStream3", txStream3) :
                new ObjectParameter("txStream3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkinobject_u", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter, txStream1Parameter, txStream2Parameter, txStream3Parameter);
        }
    
        public virtual int dt_checkoutobject(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkoutobject", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter);
        }
    
        public virtual int dt_checkoutobject_u(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkoutobject_u", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter);
        }
    
        public virtual int dt_displayoaerror(Nullable<int> iObject, Nullable<int> iresult)
        {
            var iObjectParameter = iObject.HasValue ?
                new ObjectParameter("iObject", iObject) :
                new ObjectParameter("iObject", typeof(int));
    
            var iresultParameter = iresult.HasValue ?
                new ObjectParameter("iresult", iresult) :
                new ObjectParameter("iresult", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_displayoaerror", iObjectParameter, iresultParameter);
        }
    
        public virtual int dt_displayoaerror_u(Nullable<int> iObject, Nullable<int> iresult)
        {
            var iObjectParameter = iObject.HasValue ?
                new ObjectParameter("iObject", iObject) :
                new ObjectParameter("iObject", typeof(int));
    
            var iresultParameter = iresult.HasValue ?
                new ObjectParameter("iresult", iresult) :
                new ObjectParameter("iresult", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_displayoaerror_u", iObjectParameter, iresultParameter);
        }
    
        public virtual int dt_droppropertiesbyid(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_droppropertiesbyid", idParameter, propertyParameter);
        }
    
        public virtual int dt_dropuserobjectbyid(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_dropuserobjectbyid", idParameter);
        }
    
        public virtual int dt_generateansiname(ObjectParameter name)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_generateansiname", name);
        }
    
        public virtual ObjectResult<Nullable<int>> dt_getobjwithprop(string property, string value)
        {
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_getobjwithprop", propertyParameter, valueParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> dt_getobjwithprop_u(string property, string uvalue)
        {
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var uvalueParameter = uvalue != null ?
                new ObjectParameter("uvalue", uvalue) :
                new ObjectParameter("uvalue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_getobjwithprop_u", propertyParameter, uvalueParameter);
        }
    
        public virtual ObjectResult<dt_getpropertiesbyid_Result> dt_getpropertiesbyid(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dt_getpropertiesbyid_Result>("dt_getpropertiesbyid", idParameter, propertyParameter);
        }
    
        public virtual ObjectResult<dt_getpropertiesbyid_u_Result> dt_getpropertiesbyid_u(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dt_getpropertiesbyid_u_Result>("dt_getpropertiesbyid_u", idParameter, propertyParameter);
        }
    
        public virtual int dt_getpropertiesbyid_vcs(Nullable<int> id, string property, ObjectParameter value)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_getpropertiesbyid_vcs", idParameter, propertyParameter, value);
        }
    
        public virtual int dt_getpropertiesbyid_vcs_u(Nullable<int> id, string property, ObjectParameter value)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_getpropertiesbyid_vcs_u", idParameter, propertyParameter, value);
        }
    
        public virtual int dt_isundersourcecontrol(string vchLoginName, string vchPassword, Nullable<int> iWhoToo)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iWhoTooParameter = iWhoToo.HasValue ?
                new ObjectParameter("iWhoToo", iWhoToo) :
                new ObjectParameter("iWhoToo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_isundersourcecontrol", vchLoginNameParameter, vchPasswordParameter, iWhoTooParameter);
        }
    
        public virtual int dt_isundersourcecontrol_u(string vchLoginName, string vchPassword, Nullable<int> iWhoToo)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iWhoTooParameter = iWhoToo.HasValue ?
                new ObjectParameter("iWhoToo", iWhoToo) :
                new ObjectParameter("iWhoToo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_isundersourcecontrol_u", vchLoginNameParameter, vchPasswordParameter, iWhoTooParameter);
        }
    
        public virtual int dt_removefromsourcecontrol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_removefromsourcecontrol");
        }
    
        public virtual int dt_setpropertybyid(Nullable<int> id, string property, string value, byte[] lvalue)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var lvalueParameter = lvalue != null ?
                new ObjectParameter("lvalue", lvalue) :
                new ObjectParameter("lvalue", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_setpropertybyid", idParameter, propertyParameter, valueParameter, lvalueParameter);
        }
    
        public virtual int dt_setpropertybyid_u(Nullable<int> id, string property, string uvalue, byte[] lvalue)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var uvalueParameter = uvalue != null ?
                new ObjectParameter("uvalue", uvalue) :
                new ObjectParameter("uvalue", typeof(string));
    
            var lvalueParameter = lvalue != null ?
                new ObjectParameter("lvalue", lvalue) :
                new ObjectParameter("lvalue", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_setpropertybyid_u", idParameter, propertyParameter, uvalueParameter, lvalueParameter);
        }
    
        public virtual int dt_validateloginparams(string vchLoginName, string vchPassword)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_validateloginparams", vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_validateloginparams_u(string vchLoginName, string vchPassword)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_validateloginparams_u", vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_vcsenabled()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_vcsenabled");
        }
    
        public virtual ObjectResult<Nullable<int>> dt_verstamp006()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_verstamp006");
        }
    
        public virtual ObjectResult<Nullable<int>> dt_verstamp007()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_verstamp007");
        }
    
        public virtual int dt_whocheckedout(string chObjectType, string vchObjectName, string vchLoginName, string vchPassword)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_whocheckedout", chObjectTypeParameter, vchObjectNameParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_whocheckedout_u(string chObjectType, string vchObjectName, string vchLoginName, string vchPassword)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_whocheckedout_u", chObjectTypeParameter, vchObjectNameParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int GetTimeList(string starttime, string endtime, string interval)
        {
            var starttimeParameter = starttime != null ?
                new ObjectParameter("starttime", starttime) :
                new ObjectParameter("starttime", typeof(string));
    
            var endtimeParameter = endtime != null ?
                new ObjectParameter("endtime", endtime) :
                new ObjectParameter("endtime", typeof(string));
    
            var intervalParameter = interval != null ?
                new ObjectParameter("interval", interval) :
                new ObjectParameter("interval", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetTimeList", starttimeParameter, endtimeParameter, intervalParameter);
        }
    
        public virtual int P_CalcVirtualData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_CalcVirtualData");
        }
    
        public virtual int P_GetDivisionByParent(string parents)
        {
            var parentsParameter = parents != null ?
                new ObjectParameter("parents", parents) :
                new ObjectParameter("parents", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_GetDivisionByParent", parentsParameter);
        }
    
        public virtual int P_SumDayEnergyData(string buildcode)
        {
            var buildcodeParameter = buildcode != null ?
                new ObjectParameter("Buildcode", buildcode) :
                new ObjectParameter("Buildcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_SumDayEnergyData", buildcodeParameter);
        }
    
        public virtual int P_SumHourEnergyData(string buildcode)
        {
            var buildcodeParameter = buildcode != null ?
                new ObjectParameter("Buildcode", buildcode) :
                new ObjectParameter("Buildcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_SumHourEnergyData", buildcodeParameter);
        }
    
        public virtual ObjectResult<PROC_COLLECTOR_REQUEST_Result> PROC_COLLECTOR_REQUEST(string buildingId, string gatewayId)
        {
            var buildingIdParameter = buildingId != null ?
                new ObjectParameter("buildingId", buildingId) :
                new ObjectParameter("buildingId", typeof(string));
    
            var gatewayIdParameter = gatewayId != null ?
                new ObjectParameter("gatewayId", gatewayId) :
                new ObjectParameter("gatewayId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_COLLECTOR_REQUEST_Result>("PROC_COLLECTOR_REQUEST", buildingIdParameter, gatewayIdParameter);
        }
    
        public virtual int PROC_COLLECTORDATA_INSERT(string primary, string building_id, string collectiontime, string equipmentid, string quantity, string id, string data2, string cou)
        {
            var primaryParameter = primary != null ?
                new ObjectParameter("primary", primary) :
                new ObjectParameter("primary", typeof(string));
    
            var building_idParameter = building_id != null ?
                new ObjectParameter("building_id", building_id) :
                new ObjectParameter("building_id", typeof(string));
    
            var collectiontimeParameter = collectiontime != null ?
                new ObjectParameter("collectiontime", collectiontime) :
                new ObjectParameter("collectiontime", typeof(string));
    
            var equipmentidParameter = equipmentid != null ?
                new ObjectParameter("equipmentid", equipmentid) :
                new ObjectParameter("equipmentid", typeof(string));
    
            var quantityParameter = quantity != null ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var data2Parameter = data2 != null ?
                new ObjectParameter("data2", data2) :
                new ObjectParameter("data2", typeof(string));
    
            var couParameter = cou != null ?
                new ObjectParameter("cou", cou) :
                new ObjectParameter("cou", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_COLLECTORDATA_INSERT", primaryParameter, building_idParameter, collectiontimeParameter, equipmentidParameter, quantityParameter, idParameter, data2Parameter, couParameter);
        }
    
        public virtual ObjectResult<sp_AirConditionRealtime_Result> sp_AirConditionRealtime()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_AirConditionRealtime_Result>("sp_AirConditionRealtime");
        }
    
        public virtual int sp_DSTCMD01toCMBES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DSTCMD01toCMBES");
        }
    
        public virtual ObjectResult<sp_InspectControlChart_Result> sp_InspectControlChart(string divisionID, string equipmentID, string equipmentSort, string energyCode, string staffID, string computer, Nullable<System.DateTime> beginTime, Nullable<System.DateTime> endTime)
        {
            var divisionIDParameter = divisionID != null ?
                new ObjectParameter("DivisionID", divisionID) :
                new ObjectParameter("DivisionID", typeof(string));
    
            var equipmentIDParameter = equipmentID != null ?
                new ObjectParameter("EquipmentID", equipmentID) :
                new ObjectParameter("EquipmentID", typeof(string));
    
            var equipmentSortParameter = equipmentSort != null ?
                new ObjectParameter("EquipmentSort", equipmentSort) :
                new ObjectParameter("EquipmentSort", typeof(string));
    
            var energyCodeParameter = energyCode != null ?
                new ObjectParameter("EnergyCode", energyCode) :
                new ObjectParameter("EnergyCode", typeof(string));
    
            var staffIDParameter = staffID != null ?
                new ObjectParameter("StaffID", staffID) :
                new ObjectParameter("StaffID", typeof(string));
    
            var computerParameter = computer != null ?
                new ObjectParameter("Computer", computer) :
                new ObjectParameter("Computer", typeof(string));
    
            var beginTimeParameter = beginTime.HasValue ?
                new ObjectParameter("BeginTime", beginTime) :
                new ObjectParameter("BeginTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_InspectControlChart_Result>("sp_InspectControlChart", divisionIDParameter, equipmentIDParameter, equipmentSortParameter, energyCodeParameter, staffIDParameter, computerParameter, beginTimeParameter, endTimeParameter);
        }
    
        public virtual ObjectResult<sp_InspectEnergyChart_Result> sp_InspectEnergyChart(string divisionID, string equipmentID, string equipmentSort, string energyCode, string staffID, string computer, Nullable<System.DateTime> beginTime, Nullable<System.DateTime> endTime)
        {
            var divisionIDParameter = divisionID != null ?
                new ObjectParameter("DivisionID", divisionID) :
                new ObjectParameter("DivisionID", typeof(string));
    
            var equipmentIDParameter = equipmentID != null ?
                new ObjectParameter("EquipmentID", equipmentID) :
                new ObjectParameter("EquipmentID", typeof(string));
    
            var equipmentSortParameter = equipmentSort != null ?
                new ObjectParameter("EquipmentSort", equipmentSort) :
                new ObjectParameter("EquipmentSort", typeof(string));
    
            var energyCodeParameter = energyCode != null ?
                new ObjectParameter("EnergyCode", energyCode) :
                new ObjectParameter("EnergyCode", typeof(string));
    
            var staffIDParameter = staffID != null ?
                new ObjectParameter("StaffID", staffID) :
                new ObjectParameter("StaffID", typeof(string));
    
            var computerParameter = computer != null ?
                new ObjectParameter("Computer", computer) :
                new ObjectParameter("Computer", typeof(string));
    
            var beginTimeParameter = beginTime.HasValue ?
                new ObjectParameter("BeginTime", beginTime) :
                new ObjectParameter("BeginTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_InspectEnergyChart_Result>("sp_InspectEnergyChart", divisionIDParameter, equipmentIDParameter, equipmentSortParameter, energyCodeParameter, staffIDParameter, computerParameter, beginTimeParameter, endTimeParameter);
        }
    
        public virtual int sp_MonthEnergySum(Nullable<int> yearID, Nullable<int> monthID, string divisionID, string buildCode, Nullable<int> powerSum)
        {
            var yearIDParameter = yearID.HasValue ?
                new ObjectParameter("YearID", yearID) :
                new ObjectParameter("YearID", typeof(int));
    
            var monthIDParameter = monthID.HasValue ?
                new ObjectParameter("MonthID", monthID) :
                new ObjectParameter("MonthID", typeof(int));
    
            var divisionIDParameter = divisionID != null ?
                new ObjectParameter("DivisionID", divisionID) :
                new ObjectParameter("DivisionID", typeof(string));
    
            var buildCodeParameter = buildCode != null ?
                new ObjectParameter("BuildCode", buildCode) :
                new ObjectParameter("BuildCode", typeof(string));
    
            var powerSumParameter = powerSum.HasValue ?
                new ObjectParameter("PowerSum", powerSum) :
                new ObjectParameter("PowerSum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MonthEnergySum", yearIDParameter, monthIDParameter, divisionIDParameter, buildCodeParameter, powerSumParameter);
        }
    
        public virtual int st_AlarmLimited(string divisionID)
        {
            var divisionIDParameter = divisionID != null ?
                new ObjectParameter("DivisionID", divisionID) :
                new ObjectParameter("DivisionID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("st_AlarmLimited", divisionIDParameter);
        }
    
        public virtual int st_CrossTableByRingSame(string row, string col, string orderBy, string sum, string sQL_Condition)
        {
            var rowParameter = row != null ?
                new ObjectParameter("Row", row) :
                new ObjectParameter("Row", typeof(string));
    
            var colParameter = col != null ?
                new ObjectParameter("Col", col) :
                new ObjectParameter("Col", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var sumParameter = sum != null ?
                new ObjectParameter("Sum", sum) :
                new ObjectParameter("Sum", typeof(string));
    
            var sQL_ConditionParameter = sQL_Condition != null ?
                new ObjectParameter("SQL_Condition", sQL_Condition) :
                new ObjectParameter("SQL_Condition", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("st_CrossTableByRingSame", rowParameter, colParameter, orderByParameter, sumParameter, sQL_ConditionParameter);
        }
    
        public virtual int st_CrossTableByRingSamex(string row, string col, string orderBy, string sum, string sQL_Condition)
        {
            var rowParameter = row != null ?
                new ObjectParameter("Row", row) :
                new ObjectParameter("Row", typeof(string));
    
            var colParameter = col != null ?
                new ObjectParameter("Col", col) :
                new ObjectParameter("Col", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var sumParameter = sum != null ?
                new ObjectParameter("Sum", sum) :
                new ObjectParameter("Sum", typeof(string));
    
            var sQL_ConditionParameter = sQL_Condition != null ?
                new ObjectParameter("SQL_Condition", sQL_Condition) :
                new ObjectParameter("SQL_Condition", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("st_CrossTableByRingSamex", rowParameter, colParameter, orderByParameter, sumParameter, sQL_ConditionParameter);
        }
    
        public virtual int UpdateRegionRelation()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateRegionRelation");
        }
    }
}
