//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWLWebAPI.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAirconditionSurvey
    {
        public string DivisionID { get; set; }
        public string AirconditionID { get; set; }
        public string AirconditionType { get; set; }
        public Nullable<decimal> Area { get; set; }
        public Nullable<decimal> QHeight { get; set; }
        public Nullable<decimal> DHeight { get; set; }
        public Nullable<int> RepairCycle { get; set; }
        public string CycleUnit { get; set; }
        public string Remark { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> Modifytime { get; set; }
        public string CoolEquipment { get; set; }
    }
}
