//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWLWebAPI.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAlarmRecord
    {
        public int ID { get; set; }
        public string Alarmtype { get; set; }
        public Nullable<int> AlarmID { get; set; }
        public Nullable<System.DateTime> AlarmTime { get; set; }
        public string Reason { get; set; }
        public string Suggestion { get; set; }
        public string Result { get; set; }
        public Nullable<int> AlarmLevel { get; set; }
        public string Handler { get; set; }
        public Nullable<System.DateTime> Handlertime { get; set; }
        public Nullable<decimal> RatedValue { get; set; }
        public Nullable<decimal> RealValue { get; set; }
        public string Remark { get; set; }
    }
}
