//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWLWebAPI.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAlarmConditon
    {
        public int ID { get; set; }
        public Nullable<int> BeginYearID { get; set; }
        public Nullable<int> BeginMonthID { get; set; }
        public Nullable<int> EndYearID { get; set; }
        public Nullable<int> EndMonthID { get; set; }
        public string Alarmtype { get; set; }
        public string EquipmentSort { get; set; }
        public string GradeID { get; set; }
        public string EnergyCode { get; set; }
        public string BuildCode { get; set; }
        public string EquipmentID { get; set; }
        public string CollectParameter { get; set; }
        public string Valuetype { get; set; }
        public Nullable<decimal> MinValue { get; set; }
        public Nullable<decimal> Maxvalue { get; set; }
        public string Unit { get; set; }
        public string Status { get; set; }
        public Nullable<short> Role { get; set; }
        public string HistorySame { get; set; }
        public string remark { get; set; }
        public string CollectParameterDesc { get; set; }
    }
}
