//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWLWebAPI.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBuildInfor
    {
        public int ID { get; set; }
        public string DivisionID { get; set; }
        public string BuildCode { get; set; }
        public string BuildName { get; set; }
        public string shortedName { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> CompletedTime { get; set; }
        public Nullable<short> BuildType { get; set; }
        public Nullable<short> BuildClass { get; set; }
        public Nullable<short> BuildFunction { get; set; }
        public Nullable<short> LayerNum { get; set; }
        public Nullable<decimal> BuildArea { get; set; }
        public string InfoComeFrom { get; set; }
        public string LinkPerson { get; set; }
        public string LinkTel { get; set; }
        public Nullable<System.DateTime> SurveyTime { get; set; }
        public Nullable<int> Serial { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> FreeArea { get; set; }
        public Nullable<decimal> ColdArea { get; set; }
        public Nullable<decimal> HeatArea { get; set; }
        public Nullable<int> UsedPerson { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string Active { get; set; }
        public Nullable<decimal> Window { get; set; }
        public Nullable<decimal> Wall { get; set; }
        public string AirConditionType { get; set; }
        public Nullable<decimal> QHeight { get; set; }
        public Nullable<decimal> DHeight { get; set; }
        public Nullable<decimal> RatedCool { get; set; }
        public string BuildTemp { get; set; }
        public string BuildSeion { get; set; }
        public string AreaCode { get; set; }
        public Nullable<short> UpLayerNum { get; set; }
        public Nullable<short> DownLayerNum { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string BuildDirection { get; set; }
        public string OutWindow { get; set; }
        public string GlassType { get; set; }
        public string WindowsMaterial { get; set; }
        public string CoolEquipment { get; set; }
        public string HeatEquipment { get; set; }
        public string InLamp { get; set; }
        public string OutLamp { get; set; }
        public string Inzhenliuqi { get; set; }
        public string Outzhenliuqi { get; set; }
        public string online { get; set; }
        public string ProvCode { get; set; }
        public string ProvName { get; set; }
        public string CityCode { get; set; }
        public string CityName { get; set; }
        public string Inspected { get; set; }
        public byte[] photo { get; set; }
    }
}
