//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWLWebAPI.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDailyRecord_Tran
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CollectionTime { get; set; }
        public string EquipmentID { get; set; }
        public Nullable<decimal> Ia { get; set; }
        public Nullable<decimal> Ib { get; set; }
        public Nullable<decimal> Ic { get; set; }
        public Nullable<decimal> Ua { get; set; }
        public Nullable<decimal> Ub { get; set; }
        public Nullable<decimal> Uc { get; set; }
        public Nullable<decimal> Pa { get; set; }
        public Nullable<decimal> Pb { get; set; }
        public Nullable<decimal> Pc { get; set; }
        public Nullable<decimal> I { get; set; }
        public Nullable<decimal> P { get; set; }
        public Nullable<decimal> Q { get; set; }
        public Nullable<decimal> PF { get; set; }
        public Nullable<decimal> W { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Active { get; set; }
        public Nullable<decimal> Pfa { get; set; }
        public Nullable<decimal> Pfb { get; set; }
        public Nullable<decimal> Pfc { get; set; }
    }
}
