//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWLWebAPI.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDivision
    {
        public int ID { get; set; }
        public Nullable<int> Parent_ID { get; set; }
        public string DivisionID { get; set; }
        public string DivisionName { get; set; }
        public string Address { get; set; }
        public Nullable<short> Level { get; set; }
        public string Tel { get; set; }
        public string Zip { get; set; }
        public string LinkPerson { get; set; }
        public Nullable<int> Serial { get; set; }
        public string Active { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string SendeMail { get; set; }
        public string Fax { get; set; }
        public string ProvCode { get; set; }
        public string ProvName { get; set; }
        public string CityCode { get; set; }
        public string CityName { get; set; }
        public string Apeaked { get; set; }
        public string ParentIdStr { get; set; }
    }
}
