//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWLWebAPI.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEnergyofDivisionDetail
    {
        public int DataType { get; set; }
        public string DivisionID { get; set; }
        public int ReportType { get; set; }
        public int YearID { get; set; }
        public int MonthID { get; set; }
        public string Code { get; set; }
        public string ItemType { get; set; }
        public string ItemName { get; set; }
        public string ItemUnit { get; set; }
        public Nullable<decimal> C100 { get; set; }
        public Nullable<decimal> C200 { get; set; }
        public Nullable<decimal> C301 { get; set; }
        public Nullable<decimal> C302 { get; set; }
        public Nullable<decimal> C303 { get; set; }
        public Nullable<decimal> C304 { get; set; }
        public Nullable<decimal> C305 { get; set; }
        public Nullable<decimal> C306 { get; set; }
        public Nullable<decimal> C307 { get; set; }
        public Nullable<decimal> C300 { get; set; }
        public Nullable<decimal> A000 { get; set; }
    }
}
