//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWLWebAPI.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEnergyofDivisionHearder
    {
        public string DivisionID { get; set; }
        public int ReportType { get; set; }
        public int YearID { get; set; }
        public int MonthID { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string FillUnit { get; set; }
        public string Manager { get; set; }
        public string StatPerson { get; set; }
        public string MakePerson { get; set; }
        public Nullable<System.DateTime> MakeDate { get; set; }
        public string Remark { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
    }
}
