//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWLWebAPI.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEnergyShape
    {
        public string EnergyCode { get; set; }
        public string EnergyName { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> StandardCoal { get; set; }
        public Nullable<int> Serial { get; set; }
        public string Active { get; set; }
        public string Used { get; set; }
        public string Moneyed { get; set; }
        public string Collected { get; set; }
        public string CollectedCaption { get; set; }
        public Nullable<decimal> price { get; set; }
        public string Stat { get; set; }
        public string StandardCode { get; set; }
    }
}
