//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWLWebAPI.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEquipment
    {
        public string DivisionID { get; set; }
        public string EquipmentID { get; set; }
        public string EquipmentName { get; set; }
        public string AssetsCode { get; set; }
        public string EquipmentType { get; set; }
        public string EquipmentModel { get; set; }
        public string EquipmentSpec { get; set; }
        public string EnergyType { get; set; }
        public Nullable<decimal> SumWeight { get; set; }
        public string ShapeSize { get; set; }
        public string NumericalControl { get; set; }
        public string EquipmentStatus { get; set; }
        public string UsedDepartment { get; set; }
        public string Principalman { get; set; }
        public Nullable<decimal> ElectromotorPower { get; set; }
        public Nullable<short> ElectromotorNumber { get; set; }
        public string MainPerformance { get; set; }
        public string MaintenanceRequest { get; set; }
        public string OperatedFunction { get; set; }
        public string Madein { get; set; }
        public string Manufacturer { get; set; }
        public string ManufacturerAdderess { get; set; }
        public string LeaveFactoryNo { get; set; }
        public string LeaveFactoryDate { get; set; }
        public string RelationMen { get; set; }
        public string RelationTel { get; set; }
        public string Postalcode { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
        public Nullable<System.DateTime> AcceptDate { get; set; }
        public Nullable<System.DateTime> FixDate { get; set; }
        public string FixPlace { get; set; }
        public Nullable<System.DateTime> UsedDate { get; set; }
        public Nullable<short> MaintCycle { get; set; }
        public string MaintCycleUnit { get; set; }
        public Nullable<decimal> OriginalValue { get; set; }
        public Nullable<short> DepreciationYear { get; set; }
        public Nullable<decimal> YearDepreciationRate { get; set; }
        public Nullable<decimal> ExpectationVaule { get; set; }
        public Nullable<decimal> AddUpDepreciationValue { get; set; }
        public Nullable<decimal> NetValue { get; set; }
        public string MaintManufacture { get; set; }
        public string MaintAdderess { get; set; }
        public string MaintRelationMen { get; set; }
        public string MaintRelationTel { get; set; }
        public string MaintPostalcode { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreatDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<decimal> Onlinetranslation { get; set; }
        public Nullable<System.DateTime> LastMaintDate { get; set; }
    }
}
