//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWLWebAPI.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbImageMarkerHeader
    {
        public int ID { get; set; }
        public string InspectID { get; set; }
        public string InspectProject { get; set; }
        public byte[] Map { get; set; }
        public string IveFile { get; set; }
        public string DeviceName { get; set; }
        public string LoopName { get; set; }
        public string Remark { get; set; }
        public string Active { get; set; }
    }
}
