//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWLWebAPI.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbImageMarkerDetail
    {
        public int ID { get; set; }
        public int ItemID { get; set; }
        public string Caption { get; set; }
        public string FieldName { get; set; }
        public string ParamType { get; set; }
        public string Remark { get; set; }
        public string Active { get; set; }
        public Nullable<int> serial { get; set; }
        public string DeviceName { get; set; }
        public string LoopName { get; set; }
    }
}
