//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWLWebAPI.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLimitedTarget
    {
        public int TargetType { get; set; }
        public string DivisionID { get; set; }
        public string BuildCode { get; set; }
        public int YearID { get; set; }
        public int MonthID { get; set; }
        public string EnergyCode { get; set; }
        public Nullable<decimal> LimitedQty { get; set; }
        public Nullable<decimal> UsedQty { get; set; }
        public string Active { get; set; }
        public string Remark { get; set; }
    }
}
