//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWLWebAPI.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLoopMap_OPC
    {
        public string ModuleAddress { get; set; }
        public string ItemID { get; set; }
        public string BuildCode { get; set; }
        public string DivisionID { get; set; }
        public Nullable<int> SortId { get; set; }
        public string Active { get; set; }
    }
}
