//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWLWebAPI.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLoopMapping
    {
        public int ID { get; set; }
        public Nullable<byte> ComPort { get; set; }
        public Nullable<byte> PortAddress { get; set; }
        public Nullable<byte> ADModel { get; set; }
        public string ModuleAddress { get; set; }
        public Nullable<byte> Location { get; set; }
        public string EnergyCode { get; set; }
        public string EquipmentSort { get; set; }
        public string EquipmentID { get; set; }
        public string CollectParameter { get; set; }
        public string ParameterDesc { get; set; }
        public string Model { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Iscope { get; set; }
        public Nullable<decimal> Uscope { get; set; }
        public Nullable<decimal> Iratio { get; set; }
        public Nullable<decimal> Uratio { get; set; }
        public string Active { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> Modifytime { get; set; }
        public string SameID { get; set; }
        public string IsMain { get; set; }
        public string UnMain { get; set; }
        public Nullable<decimal> RatedPower { get; set; }
        public Nullable<decimal> ElectromotorRatio { get; set; }
        public Nullable<int> BVLen { get; set; }
        public string GUNo { get; set; }
        public string remark { get; set; }
        public string SecondCollected { get; set; }
        public string DivisionID { get; set; }
        public string DailyRecord { get; set; }
        public string UserID { get; set; }
        public string BuildCode { get; set; }
        public string OPC { get; set; }
        public string SubSys { get; set; }
    }
}
