//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWLWebAPI.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPowerCollection
    {
        public int ID { get; set; }
        public string DivisionID { get; set; }
        public Nullable<System.DateTime> CollectionTime { get; set; }
        public string EquipmentID { get; set; }
        public string EquipmentSort { get; set; }
        public Nullable<decimal> Ia { get; set; }
        public Nullable<decimal> Ib { get; set; }
        public Nullable<decimal> Ic { get; set; }
        public Nullable<decimal> Ua { get; set; }
        public Nullable<decimal> Ub { get; set; }
        public Nullable<decimal> Uc { get; set; }
        public Nullable<decimal> HZ { get; set; }
        public Nullable<decimal> P { get; set; }
        public Nullable<decimal> Pa { get; set; }
        public Nullable<decimal> Pb { get; set; }
        public Nullable<decimal> Pc { get; set; }
        public Nullable<decimal> Q { get; set; }
        public Nullable<decimal> Qa { get; set; }
        public Nullable<decimal> Qb { get; set; }
        public Nullable<decimal> Qc { get; set; }
        public Nullable<decimal> S { get; set; }
        public Nullable<decimal> Sa { get; set; }
        public Nullable<decimal> Sb { get; set; }
        public Nullable<decimal> Sc { get; set; }
        public Nullable<decimal> PF { get; set; }
        public Nullable<decimal> PFa { get; set; }
        public Nullable<decimal> PFb { get; set; }
        public Nullable<decimal> PFc { get; set; }
        public Nullable<decimal> P1 { get; set; }
        public Nullable<decimal> P1a { get; set; }
        public Nullable<decimal> P1b { get; set; }
        public Nullable<decimal> P1c { get; set; }
        public Nullable<decimal> Px { get; set; }
        public Nullable<decimal> Pxa { get; set; }
        public Nullable<decimal> Pxb { get; set; }
        public Nullable<decimal> Pxc { get; set; }
        public Nullable<decimal> Q1 { get; set; }
        public Nullable<decimal> Q1a { get; set; }
        public Nullable<decimal> Q1b { get; set; }
        public Nullable<decimal> Q1c { get; set; }
        public Nullable<decimal> Wpz { get; set; }
        public Nullable<decimal> Wpf { get; set; }
        public Nullable<decimal> Wqz { get; set; }
        public Nullable<decimal> Wqf { get; set; }
        public Nullable<decimal> W { get; set; }
        public Nullable<decimal> Wa { get; set; }
        public Nullable<decimal> Wb { get; set; }
        public Nullable<decimal> Wc { get; set; }
        public Nullable<decimal> I { get; set; }
        public Nullable<decimal> U { get; set; }
        public Nullable<decimal> Wp { get; set; }
        public Nullable<decimal> Wq { get; set; }
        public Nullable<decimal> WpzR { get; set; }
        public Nullable<decimal> WpfR { get; set; }
        public Nullable<decimal> WqzR { get; set; }
        public Nullable<decimal> WqfR { get; set; }
        public Nullable<decimal> WpR { get; set; }
        public Nullable<decimal> WqR { get; set; }
        public Nullable<decimal> WR { get; set; }
        public Nullable<decimal> WaR { get; set; }
        public Nullable<decimal> WbR { get; set; }
        public Nullable<decimal> WcR { get; set; }
        public Nullable<decimal> YRatio { get; set; }
        public string Active { get; set; }
    }
}
