//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWLWebAPI.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbReportList
    {
        public int ID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string itemName { get; set; }
        public Nullable<int> Serial { get; set; }
        public string active { get; set; }
    }
}
