//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWLWebAPI.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbStaffPurview
    {
        public string StaffID { get; set; }
        public string StaffType { get; set; }
        public string ModuleName { get; set; }
        public string PowerLogin { get; set; }
        public string PowerAdd { get; set; }
        public string PowerEdit { get; set; }
        public string PowerDel { get; set; }
        public string PowerPrint { get; set; }
        public string PowerQuery { get; set; }
        public Nullable<int> Serial { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> Modifytime { get; set; }
        public string MenuID { get; set; }
    }
}
