//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWLWebAPI.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_CollectionMaxId
    {
        public string DivisionID { get; set; }
        public string EquipmentID { get; set; }
        public string EquipmentSort { get; set; }
        public string EnergyCode { get; set; }
        public int Paramtype { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<System.DateTime> CollectionTime { get; set; }
        public Nullable<decimal> LastQuantity { get; set; }
    }
}
