//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWLWebAPI.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_EnergySurveyHeader
    {
        public int ID { get; set; }
        public string BlockID { get; set; }
        public Nullable<int> YearID { get; set; }
        public Nullable<int> MonthID { get; set; }
        public string DivisionID { get; set; }
        public Nullable<decimal> BuildArea { get; set; }
        public Nullable<int> StaffNumber { get; set; }
        public string Remark { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string BuildCode { get; set; }
        public string Active { get; set; }
        public string FromEmail { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<int> Serial { get; set; }
        public string ReplayEmail { get; set; }
        public Nullable<int> AuthorizedPerson { get; set; }
    }
}
